//
//  HTTP+HeaderField.swift
//  HttpUtils
//
//  Created by Wesley on 8/16/20.
//

public extension HTTP.Header {
    enum RequestField: String {
        case accept = "Accept"
        case acceptableInstanceManipulations = "A-IM"
        case acceptCharset = "Accept-Charset"
        case acceptDatetime = "Accept-Datetime"
        case acceptEncoding = "Accept-Encoding"
        case acceptLanguage = "Accept-Language"
        case accessControlRequestMethod = "Access-Control-Request-Method"
        case accessControlRequestHeaders = "Access-Control-Request-Headers"
        case authorization = "Authorization"
        case cacheControl = "Cache-Control"
        case connection = "Connection"
        case contentEncoding = "Content-Encoding"
        case contentLength = "Content-Length"
        case contentMD5 = "Content-MD5"
        case contentType = "Content-Type"
        case cookie = "Cookie"
        case date = "Date"
        case expect = "Expect"
        case forwarded = "Forwarded"
        case from = "From"
        case host = "Host"
        case http2Settings = "HTTP2-Settings"
        case ifMatch = "If-Match"
        case ifModifiedSince = "If-Modified-Since"
        case ifNoneMatch = "If-None-Match"
        case ifRange = "If-Range"
        case ifUnmodifiedSince = "If-Unmodified-Since"
        case maxForwards = "Max-Forwards"
        case origin = "Origin"
        case pragma = "Pragma"
        case proxyAuthorization = "Proxy-Authorization"
        case range = "Range"
        case referer = "Referer"
        case transferEncodings = "TE"
        case trailer = "Trailer"
        case transferEncoding = "Transfer-Encoding"
        case userAgent = "User-Agent"
        case upgrade = "Upgrade"
        case via = "Via"
        case warning = "Warning"
    }
    
    enum ResponseField: String {
        case accessControlAllowOrigin = "Access-Control-Allow-Origin"
        case accessControlAllowCredentials = "Access-Control-Allow-Credentials"
        case accessControlExposeHeaders = "Access-Control-Expose-Headers"
        case accessControlMaxAge = "Access-Control-Max-Age"
        case accessControlAllowMethods = "Access-Control-Allow-Methods"
        case accessControlAllowHeaders = "Access-Control-Allow-Headers"
        case acceptPatch = "Accept-Patch"
        case acceptRanges = "Accept-Ranges"
        case age = "Age"
        case allow = "Allow"
        case alternativeServices = "Alt-Svc"
        case cacheControl = "Cache-Control"
        case connection = "Connection"
        case contentDisposition = "Content-Disposition"
        case contentEncoding = "Content-Encoding"
        case contentLanguage = "Content-Language"
        case contentLength = "Content-Length"
        case contentLocation = "Content-Location"
        case contentMD5 = "Content-MD5"
        case contentRange = "Content-Range"
        case contentType = "Content-Type"
        case date = "Date"
        case deltaBase = "Delta-Base"
        case eTag = "ETag"
        case expires = "Expires"
        case instanceManipulations = "IM"
        case lastModified = "Last-Modified"
        case link = "Link"
        case location = "Location"
        case p3p = "P3P"
        case pragma = "Pragma"
        case proxyAuthenticate = "Proxy-Authenticate"
        case publicKeyPins = "Public-Key-Pins"
        case retryAfter = "Retry-After"
        case server = "Server"
        case setCookie = "Set-Cookie"
        case strictTransportSecurity = "Strict-Transport-Security"
        case trackingStatus = "Tk"
        case trailer = "Trailer"
        case transferEncoding = "Transfer-Encoding"
        case upgrade = "Upgrade"
        case vary = "Vary"
        case via = "Via"
        case warning = "Warning"
        case wwwAuthenticate = "WWW-Authenticate"
        case xFrameOptions = "X-Frame-Options"
    }
}
